### ISSUE TITLE
no gpu found

### ISSUE THREAD

**Issue by Lotsoliu** [feifeiobama/InfluenceCL#2]
![1280X1280](https://github.com/feifeiobama/InfluenceCL/assets/127647910/12279027-4666-45bb-971f-bea92cbfaa68)
when comes to sel_epoch(49), it seems not work with 2080ti

**Comment by feifeiobama** [comment]
This is fine.

Influence-based selection is implemented on CPU by default, because it runs slower on GPU than CPU. The computational bottleneck is the conjugate gradient method ([line 88-92 in influence_ntk.py](https://github.com/feifeiobama/InfluenceCL/blob/main/utils/influence_ntk.py#L88)), and it cannot be alleviated by replacing the backend with GPU (tested with [this implementation](https://docs.backpack.pt/en/master/use_cases/example_cg_newton.html#writing-the-optimizer)).

This is also the reason why we only update the replay buffer during the last epoch :(

**Comment by jimmyluong710** [comment]
@feifeiobama  you said: "This is also the reason why we only update the replay buffer during the last epoch", so when come in new task, will the new task still use CPU to train from epoch 0th?
if that's true, it will take too long time to finish all the tasks, right?
do you have any solution to re-use GPU from epoch 0th for the new task?
tks.

**Comment by feifeiobama** [comment]
> @feifeiobama you said: "This is also the reason why we only update the replay buffer during the last epoch", so when come in new task, will the new task still use CPU to train from epoch 0th? if that's true, it will take too long time to finish all the tasks, right? do you have any solution to re-use GPU from epoch 0th for the new task? tks.

No, the training always uses GPU, only the sample selection step uses CPU.

**Comment by ghost** [comment]
> > @feifeiobama you said: "This is also the reason why we only update the replay buffer during the last epoch", so when come in new task, will the new task still use CPU to train from epoch 0th? if that's true, it will take too long time to finish all the tasks, right? do you have any solution to re-use GPU from epoch 0th for the new task? tks.
> 
> No, the training always uses GPU, only the sample selection step uses CPU.

Is TPU faster than CPU at last epoch each iteration?
when increasing memory size up to 1000, the model becomes too slow, it might take over 2 days to complete.

**Comment by feifeiobama** [comment]
> > > @feifeiobama you said: "This is also the reason why we only update the replay buffer during the last epoch", so when come in new task, will the new task still use CPU to train from epoch 0th? if that's true, it will take too long time to finish all the tasks, right? do you have any solution to re-use GPU from epoch 0th for the new task? tks.
> > 
> > 
> > No, the training always uses GPU, only the sample selection step uses CPU.
> 
> Is TPU faster than CPU at last epoch each iteration? when increasing memory size up to 1000, the model becomes too slow, it might take over 2 days to complete.

I remember it being much faster than that, even with a memory size of 1000. May I ask if you are following the same dataset protocol (e.g. using downsampled images from miniImageNet)?

**Comment by ghost** [comment]
> > > > @feifeiobama you said: "This is also the reason why we only update the replay buffer during the last epoch", so when come in new task, will the new task still use CPU to train from epoch 0th? if that's true, it will take too long time to finish all the tasks, right? do you have any solution to re-use GPU from epoch 0th for the new task? tks.
> > > 
> > > 
> > > No, the training always uses GPU, only the sample selection step uses CPU.
> > 
> > 
> > Is TPU faster than CPU at last epoch each iteration? when increasing memory size up to 1000, the model becomes too slow, it might take over 2 days to complete.
> 
> I remember it being much faster than that, even with a memory size of 1000. May I ask if you are following the same dataset protocol (e.g. using downsampled images from miniImageNet)?

i ran this command following in README:
 "python3 utils/main.py --model soif --load_best_args --dataset seq-cifar100 --buffer_size 1000".
 Then I waited about 2 days to get the results. Is there any error with this, can you show me how to complete the run time around 2h? (i used GTX 1660 Super for trainning)

**Comment by feifeiobama** [comment]
> > > > > @feifeiobama you said: "This is also the reason why we only update the replay buffer during the last epoch", so when come in new task, will the new task still use CPU to train from epoch 0th? if that's true, it will take too long time to finish all the tasks, right? do you have any solution to re-use GPU from epoch 0th for the new task? tks.
> > > > 
> > > > 
> > > > No, the training always uses GPU, only the sample selection step uses CPU.
> > > 
> > > 
> > > Is TPU faster than CPU at last epoch each iteration? when increasing memory size up to 1000, the model becomes too slow, it might take over 2 days to complete.
> > 
> > 
> > I remember it being much faster than that, even with a memory size of 1000. May I ask if you are following the same dataset protocol (e.g. using downsampled images from miniImageNet)?
> 
> i ran this command following in README: "python3 utils/main.py --model soif --load_best_args --dataset seq-cifar100 --buffer_size 1000". Then I waited about 2 days to get the results. Is there any error with this, can you show me how to complete the run time around 2h? (i used GTX 1660 Super for trainning)

Thank you for the detailed description. Since you indicate that you are running the experiment on a personal computer, the resulting overlong runtime is possible, especially given the high CPU & memory usage when computing influence functions on the CPU.

To verify this, I suggest monitoring CPU & memory usage during the experiments, and if this is indeed the case, you might consider moving the influence computation to the GPU or finding a server.
